backend:
  name: github
  repo: kuankuantj2831/kuankuantj2831.github.io
  branch: main
  site_domain: kuankuantj2831.github.io

publish_mode: editorial_workflow

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "标签", name: "tags", widget: "list", optional: true }
      - { label: "分类", name: "categories", widget: "list", optional: true }
      - { label: "正文", name: "body", widget: "markdown" }
